spring:
  application:
    name: ludotheque

  datasource:
    url: jdbc:sqlserver://localhost;databasename=LUDO_DB;encrypt=false
    username: LUDO_USER
    password: "user_456"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
          format_sql: true
